name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/**"

jobs:
  lint-test-build:
    permissions:
      contents: read
    runs-on: ubuntu-8c-32gb

    defaults:
      run:
        working-directory: org.knime.ui.js

    steps:
      - uses: actions/checkout@v5
        # Sonar runs in Jenkins for the whole repo due to the mix of Java and JS
        # with:
        #   fetch-depth: 0 # full history for SonarCloud
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: org.knime.ui.js/package.json
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: org.knime.ui.js/pnpm-lock.yaml
          node-version-file: "org.knime.ui.js/package.json"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Lint and format
        run: pnpm run ci:lint-format

      - name: Type check
        run: pnpm run type-check

      - name: Run coverage
        run: pnpm run coverage

      - name: Build for CI
        run: pnpm run build:ci

      - name: Audit
        run: pnpm run audit

      # Sonar runs in Jenkins for the whole repo due to the mix of Java and JS
      # - name: Sonar scan
      #   if: github.actor != 'dependabot[bot]'
      #   uses: SonarSource/sonarqube-scan-action@v6
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  e2e-tests:
    runs-on: ubuntu-8c-32gb
    defaults:
      run:
        working-directory: org.knime.ui.js
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: org.knime.ui.js/package.json

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: org.knime.ui.js/pnpm-lock.yaml
          node-version-file: "org.knime.ui.js/package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install

      - name: Run e2e tests
        run: pnpm run test:e2e

      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-artifacts
          path: |
            org.knime.ui.js/playwright-report/**
            org.knime.ui.js/test-results/**
